viral_content_research:
  description: >
    Research and analyze current trending topics using Google Trends, news websites, and social media platforms.
    Focus on topics that have high viral potential and are relevant to our target audience.
    Provide detailed context and engagement metrics for each topic.
  expected_output: >
    A detailed analysis of the top trending topics including:
    - Topic name and description
    - Current engagement metrics
    - Key hashtags and related terms
    - Potential viral angles
  agent: content_researcher

viral_content_tweet:
  description: >
    Using the research provided, create compelling tweets that have high viral potential.
    Each tweet should:
    - Be optimized for engagement
    - Include relevant hashtags
    - Follow Twitter best practices
    - Have a clear hook or call-to-action
  expected_output: >
    10 optimized tweets with hashtags only.No repetition of the tweets check in tweet.txt file  before the tweet is published to stop repition.no notes and no description.
  agent: tweet_writer

